### ISSUE TITLE
Allow colour styling

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/notdonemywebsite#3]
This is a nut I have yet to crack, it's proving to be a bit tricky with the live iFrame preview. If anyone has ideas on how to implement this, I'd really appreciate it :)

**Comment by gmemstr** [comment]
Should add, the markup for the colour selectors is already in the HTML, just commented out since I haven't been able to get it working

**Comment by OvidiuToma** [comment]
Hi @gmemstr, I'll gladly take a shot a this. 

I've managed to clone the repo and i've played around with the js. 
My question is: what are the color inputs supposed to do? I see that they have the id's primary and secondary. 
1. Do you except them to change the overall look of layout? Let's say the default theme colors are blue and yellow, those fields should just have the ability to change those 2 colors?
2. Or do you want individual elements in the layouts to be changed independently? Like the ability to click on an element and change the background color and text-color.

**Comment by gmemstr** [comment]
@OvidiuToma My idea was to allow templates to define two primary colours which can be changed by the user. Should just change the overall look - individual editing would be nice but there's currently no way of selecting those manually.

**Comment by OvidiuToma** [comment]
@gmemstr Alright, I've finished the functionality and I will create the pull request in the following hours.

**Comment by OvidiuToma** [comment]
@gmemstr Added pr: https://github.com/gmemstr/notdonemywebsite/pull/20 . Ping me if you want me to change something.
